### ISSUE TITLE
Recipe delay problem

### ISSUE THREAD

**Issue by Max-Headroom** [BernhardSchlegel/BierBot-Bricks#12]
I'm only testing and  simulating fermenting to see if it all works.
I've set up my test recipe to do fermenting at 17C and after 1 day to start secondary fermenting at 13C.
All worked well for a few hours doing 17C, but after only 4hours it went to secondary at 13C. So, not a 1 day wait.

I didn't make changes to recipe while running. Although I have unplugged the brick 2 or 3 times (let's call is simulating power failures).

**Comment by Max-Headroom** [comment]
No, this is all wrong. Maybe I'm missing something.
Created a new recipe. Fermenting at 17C
Second stage at 13C after 3 days.

Start recipe. first stage run for a few seconds and then it jumps straight to second.

Side Issue: I can't delete recipe. It deletes on current view, but when I reload the page it still shows the deleted recipe.

**Comment by BernhardSchlegel** [comment]
Hey Max-Headroom, sorry to hear. Can you invite my to your brewery, so I can have a look? Name is "Bernhard".

Thanks!

**Comment by Max-Headroom** [comment]
Hi
How do I do that?

Btw the delete recipe problem seems like it is just a browser/software 
cache problem.

Regards
Quentin

**Comment by BernhardSchlegel** [comment]
Hey quentin, just head over to recipes and insert a fermentation step. You can then drag him to be the first one.

**Comment by BernhardSchlegel** [comment]
Hey quentin, I think I found and fixed it. Please let me know if the problem persists! 

PS: Please consider giving this repo a star ⭐ 👍

**Comment by Max-Headroom** [comment]
Hi
No, still the same.
I've deleted my recipes, made a new one. CNRTL- F5 to load for server.
Quite a few weird funny things going on now. ie, even if I delete a 
recipe. I still got to stop the auto process.
Can't rename a recipe sometimes for some reason. etc.

But still the same, as soon as I start a recipe, after a few secs, it 
jumps to the next phase.


  Sure as admin you can get into my account, same email as this.


Regards
Quentin.

**Comment by BernhardSchlegel** [comment]
Hi Quentin,

I'm afraid, you need to be a little more verbose with your error descriptions so I can try to fix it :)

"even if I delete a recipe, I still got to stop the auto process.": If you mean "deleting a recipe from the recipebook", that will not affect your current auto process. But that's intended behaviour. 

Do you have a stable internet connection? Can you paste the results of a speedtest here?

Also: I don't see your E-Mail here. Can you contact at hello@bierbot.com to share the apikey ? 

Thanks-a-lot,
Bernhard.

**Comment by BernhardSchlegel** [comment]
unintentional close

**Comment by Max-Headroom** [comment]
Newbie problem
