### ISSUE TITLE
Manual update, flashing the brick

### ISSUE THREAD

**Issue by hometm** [BernhardSchlegel/BierBot-Bricks#5]
I wasted some time during flash of the TH16. I guess, some others could have the same trouble. 

Could you please add the note, that TH16 button must be pressed, during connecting the USB/Serial converter. Otherwise, the downloader will not recognise the device. 

A second note (that made me considering) was the jumper setting of programming voltage (3.3 Volts).

Thanks, 
Tobias

**Comment by BernhardSchlegel** [comment]
Hi Tobias,

thanks for reaching out and sorry for the inconvenience.

I'll link the YouTube video that explains the process in greater detail AND add the two notes (pressing the button, 3.3V)

Cheers,
Bernhard.

**Comment by BernhardSchlegel** [comment]
Readme updated
